// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXkmcbAl8nY3T4PRaj2Am9AQNSO-jAjP4',
    appId: '1:778851391746:web:2063bbd1924a0acb014a1b',
    messagingSenderId: '778851391746',
    projectId: 'talky-2026',
    authDomain: 'talky-2026.firebaseapp.com',
    databaseURL: 'https://talky-2026-default-rtdb.firebaseio.com',
    storageBucket: 'talky-2026.firebasestorage.app',
    measurementId: 'G-DZ0Y3LJJXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZZ3-nee1i2BfMzxUSpyey7ZZO9yDTclM',
    appId: '1:778851391746:android:c989a00085117a7a014a1b',
    messagingSenderId: '778851391746',
    projectId: 'talky-2026',
    databaseURL: 'https://talky-2026-default-rtdb.firebaseio.com',
    storageBucket: 'talky-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlFSkqoytmJxDGiC-KUhpgkbOFdbRjc4A',
    appId: '1:778851391746:ios:8e2b1c3d339a8918014a1b',
    messagingSenderId: '778851391746',
    projectId: 'talky-2026',
    databaseURL: 'https://talky-2026-default-rtdb.firebaseio.com',
    storageBucket: 'talky-2026.firebasestorage.app',
    androidClientId: '778851391746-bbu44ab95l6nnskjcih3b2th14ie9mbp.apps.googleusercontent.com',
    iosClientId: '778851391746-qli3npipbakbp5pqhh6gcncah9p5bdrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlFSkqoytmJxDGiC-KUhpgkbOFdbRjc4A',
    appId: '1:778851391746:ios:8e2b1c3d339a8918014a1b',
    messagingSenderId: '778851391746',
    projectId: 'talky-2026',
    databaseURL: 'https://talky-2026-default-rtdb.firebaseio.com',
    storageBucket: 'talky-2026.firebasestorage.app',
    androidClientId: '778851391746-bbu44ab95l6nnskjcih3b2th14ie9mbp.apps.googleusercontent.com',
    iosClientId: '778851391746-qli3npipbakbp5pqhh6gcncah9p5bdrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkyFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXkmcbAl8nY3T4PRaj2Am9AQNSO-jAjP4',
    appId: '1:778851391746:web:01ad7d17147cab86014a1b',
    messagingSenderId: '778851391746',
    projectId: 'talky-2026',
    authDomain: 'talky-2026.firebaseapp.com',
    databaseURL: 'https://talky-2026-default-rtdb.firebaseio.com',
    storageBucket: 'talky-2026.firebasestorage.app',
    measurementId: 'G-HE1LEXJ6SR',
  );
}
